@ main.s
@ A main function to call "roll dice", prints out the sequence of rolls 
@ generated by "roll_dice", and call "count_run" to count and print out the size
@ of each run found and the total number of runs
@ Will Bouasisavath - 007547473



.syntax unified

.section .rodata
fmt1: .string "%d,"
nl:   .string "\n"

.data
array: .space 400

.text
.global main

main:

    push {r4, r5, lr}

    ldr r0, =array
    bl roll_dice
    
    mov r4, 0 @ counter/index
    ldr r5, =array

.print:

    cmp r4, 100
    mov r0, 0
    blge fflush
    bge .count

    ldr r0, =fmt1
    ldr r1, [r5, r4, lsl 2] @ index * 4
    bl printf

    add r4, r4, 1
    b .print

.count:

    ldr r0, =nl
    bl printf

    ldr r0, =array
    bl count_run

.exit:

    pop {r4, r5, lr}

    mov r0, 0
    mov r7, 1
    svc 0